### ISSUE TITLE
Ctrl+F9 doesn't work to hide/display Secondary lateral panel

### ISSUE THREAD

**Issue by LazyKent** [pragha-music-player/pragha#73] opened 2015-01-20 19:03 UTC
'Ctrl+F9' doesn't work to hide/display Secondary lateral panel.
It works from the menu "View" -> "Secondary lateral panel", though.
Built for openSUSE.

**Comment by matiasdelellis** [comment] 2015-01-20 19:18
D'Oh!.
You're right. I just checked it. :sweat:

Well, at this moment I'm trying to fix the progress bar in Gtk >= 3.14. Then I see this and make a new release!.

Thank you for report it and always participate!. :wink: 

Regards.

**Comment by LazyKent** [comment] 2015-01-20 19:48
And, please, after that. Can Pragha remember its view (active panels) for the next start. At the moment the first lateral panel is disabled, if it is hidden before exit. And the secondary panel is always active at start.

**Comment by matiasdelellis** [comment] 2015-01-20 20:03
D'Oh!. Again.. You're right.. haha.

Ok. As soon as I can I will try to fix it.

**Comment by matiasdelellis** [comment] 2015-02-16 15:51
Hi @LazyKent 
I had to change Control+F9 to F10.  It's strange, but this combination does not like to Gtk or somewhere else.. :disappointed:

Well, It's okay?

**Comment by matiasdelellis** [comment] 2015-02-17 22:03
D'Oh!. F10 is accelerator to menubar.. :s

**Comment by matiasdelellis** [comment] 2015-02-21 21:53
Hi @LazyKent 
I'll revert the change to F10, the problem is that Control+F9 is setted as "Switch to 9 desktop" (Something similar =) in xfwm4 settigns. :disappointed:

**Comment by LazyKent** [comment] 2015-02-22 14:48
Hi, matiasdelellis.
I've updated to 1.3.2.1. I see "Control+F9" in the menu as an accelerator, and it doesn't work of course.

F10 opens the main menu "Playback".

**Comment by matiasdelellis** [comment] 2015-02-22 15:34
Yes. Revert it due F10 is a standard accel to show menubar..  Try it in any application. ;)

Now temporarily returned to be Control+F9 but not working due to a conflict with xfwm setting.. You are using xfce? Please, see on Keyboard tab of Xfwm dialog.

**Comment by LazyKent** [comment] 2015-02-22 16:21
I'm using Xfce. Removing "Control+F9" combination in Xfwm keyboard settings helps. Then Pragha accepts "Control+F9" and displays/hides the secondary panel. Not a good way, though. Maybe change to "Ctrl+any_vacant_letter"?

**Comment by matiasdelellis** [comment] 2015-02-22 16:47
> Not a good way, though.

True.. 

> Maybe change to "Ctrl+any_vacant_letter"?

Yes. It's the idea, but we need to be consistent with "First lateral panel", that now is F9 and is "standard.."
Of course we can replace both, if they are consistent between them and more or less standard. No problem with that..

**Comment by matiasdelellis** [comment] 2016-09-04 19:57
A year and a half later, but I think that whit this convinacton we can close this bug ..  :sweat_smile:

Work on Xfce and Gnome, It is consistent with the left panel, and is shared with another application..

**Closed by matiasdelellis** 2016-09-04 19:57 UTC
