### ISSUE TITLE
Drag'n'drop doesn't work in playlist

### ISSUE THREAD

**Issue by wymiatacz** [pragha-music-player/pragha#104] opened 2016-07-12 20:29 UTC
Any dragged and dropped item disappears (is removed from playlist) instead of being reordered.

Happens in Pragha 9019ac28bc3c5e075cac171ebed9e8da047e4c43 as well as in pragha-1.3.3-2.fc24.x86_64 running on Fedora 24 XFCE
##

**Comment by matiasdelellis** [comment] 2016-07-18 14:30
Drag'n'drop from and to playlist???

Just develop Pragha on Fedora and realy is tested.. You are sure about it?

**Comment by miguelgaliza** [comment] 2016-08-29 16:46
Hi, both fedora 24  and opensuse  tumbleweed so does, to move a song in the playlist disappears.
Sorry for my bad english.

**Comment by matiasdelellis** [comment] 2016-08-29 22:05
Hi,
Please... Can write a list of actions to reproduce it?? Or an tiny video?? Thanks..

P.s: Sorry.. Much work and little time to dedicate to my projects, but soon a new version .. :wink:

**Comment by matiasdelellis** [comment] 2016-08-29 22:26
Ohhhh...
Sooo sorrryyyyyy.. I can reproduce it... :disappointed: 

Right now I start to investigate better..

**Comment by matiasdelellis** [comment] 2016-08-30 13:09
Ok.. After some tests can reproudce it on Fedora 24 with Gtk 3.20, but not on any previous distribution, therefore it seems to be a Gtk+3 regression.. :disappointed: 

Still investigating.. :wink:

**Comment by nick87720z** [comment] 2016-09-18 06:57
Hello. I noticed it in todo for 1.4.0. But in 1.3.3 it already works. More exactly, when i'm moving to some position to drop, drop place is marked by line... however, it may have one of two colors, which may indicate, that drop will or will not happen. Later case usually happens only when i try to move track to end and move object to far after playlist.

**Comment by nick87720z** [comment] 2016-09-18 07:00
I wass wrong about two colors, but when moving to end or start of playlist, it indeed have chance to not happen.

**Comment by matiasdelellis** [comment] 2016-11-24 19:25
Hi @wymiatacz @miguelgaliza 
Is definitely a bug on gtk and luckily we already have an official answer.. 😄 
See: https://bugzilla.gnome.org/show_bug.cgi?id=774726

Hi @nick87720z 
> I wass wrong about two colors, but when moving to end or start of playlist, it indeed have chance to not happen.

This is really a Pragha problem and I will solve it soon .. 😉 

Thank you all for participating and patience.. 😄

**Comment by matiasdelellis** [comment] 2017-01-11 16:54
Fixed on future releases of gtk 3.20, 3.22 and 3.90...

https://git.gnome.org/browse/gtk+/commit/?h=gtk-3-20

:smiley:

**Comment by wymiatacz** [comment] 2017-01-27 16:28
Got gtk3-3.22.7-1 from Fedora 25 updates.
Drag'n'drop works again.
Thanks :)

**Closed** 2019-08-13 23:00 UTC
