### ISSUE TITLE
"Playlist -> Add location" adds only the first item of an m3u playlist

### ISSUE THREAD

**Issue by yurkobb** [pragha-music-player/pragha#81] opened 2015-06-25 12:21 UTC
In many cases (like archive.org for example), sites provide a "stream URL" pointing to an m3u playlist that contains more URI's than just one ([example](https://archive.org/details/GeminiTri-Mirror), [another one](http://www.restingbell.net/releases/rb103-guide)). Typically this is a way to stream an entire album to a player. Currently Pragha only adds the first song in the playlist and ignores the rest. It should add all the songs in the m3u file instead.

**Comment by matiasdelellis** [comment] 2015-06-26 00:20
Hi,
You refers to menu "Playlist-> Add location"?
You're right, but this is because it is thought to radios. The idea was to add only a radio to the lateral penel. Not for playlist.. :worried:

I would like to fix, :wink: 
The problem is how to correctly differentiate radio and playlists without complicating the interface.

What do you suggest?.
How other players behave?.

Regards,
Thank you for participating,
Matias

**Comment by yurkobb** [comment] 2015-07-02 20:04
Thanks for your reply, Matias! Regarding the differentiation between radio and playlist - to me as a user the most natural place for a collection of radios would be as a tab in the same place where we have the library browser now (on the left). So that one would switch between browsing radios and local files on the left.

But the current functionality of "Playlist -> Add location" clearly suggests that we add something to the playlist, not to some collection of radios (bookmarks?), unrelated do the playlist.

So I'd suggest that if the user adds an m3u URL to the the playlist, we parse it and add all the tracks that are inside into the playlist. If it is an internet radio, most likely it will contain only one track (i.e. stream), so nothing will change for the user in the case of radio.

But if the m3u URL has multiple tracks, then it is not a radio, but probably something like an album. So in both cases it makes sense to just add to the playlist the amount of tracks that is available in the m3u file (this is what VLC does by the way).

And thanks for your hard word:)

Yury

**Comment by matiasdelellis** [comment] 2015-07-12 02:04
Hi Yury,
I hope the last commit meet your expectations.. :smile:

In summary:
 * Allways append all songs
 * If you not provide a name, just add it to playlist
 * If provide a name, add these to sidebar as Name, Name 1, Name 2,.. Name N.

This last point is just what we wanted to avoid, but I think for now it is enough.. :relieved:

Please, Test it.
Regards,
Matias.

**Comment by yurkobb** [comment] 2015-08-19 14:36
Works perfectly:) Thanks man.

**Comment by matiasdelellis** [comment] 2015-09-24 02:08
Ok.
So fixed on Pragha v1.3.3 

Regards, :wink:

**Closed by matiasdelellis** 2015-09-24 02:08 UTC
