### ISSUE TITLE
Big icon Pragha on volume control menu (MPRIS)

### ISSUE THREAD

**Issue by varlesh** [pragha-music-player/pragha#80] opened 2015-04-12 03:12 UTC
![2015-04-12 06 02 33](https://cloud.githubusercontent.com/assets/8083855/7104240/73f6b340-e0da-11e4-855b-8217234cbc2f.png)

This happens because it use PNG format. If use SVG - displayed normally.
I create pragha.svg , please use it ))
Preview:
![pragha](https://cloud.githubusercontent.com/assets/8083855/7104248/d7e7fe9a-e0da-11e4-97c4-85b14c5735a1.png)

Download SVG:
http://www.datafilehost.com/d/f6c8ad22

**Comment by matiasdelellis** [comment] 2015-04-12 12:43
Hi,
You're right. The Pragha problem is that only provide 128x128 icons. However the MPRIS standard, no make any reference to the size of icons. Just not interested in it. haha.. ;)

Well, in short, this is a "regression" in gtk 3.14 which should be considered in ubuntu-sound-indicator

See for example:
 * https://github.com/pragha-music-player/pragha/commit/916384aefd313158699ab8d480a813f757ca5201
 * https://github.com/pragha-music-player/pragha/commit/b952e34d06bd24792635cbe17b766a6475ddeee0
 * https://github.com/GNOME/geary/commit/f1fc86f2dbd1ca6b10296744b88267d18d7a25e7
 * https://github.com/GNOME/geary/commit/d7e8136cd56cd5f5024101cfdde8e66107e4cc8a

Thanks for the icon.
Had lost the original svg, so never complete the rest of the icons. :sweat_smile:

However I will not use your icon because I'm talking to a designer friend who has the original font for to make a new icon. but leaves open bug, because it's obviously something to improve..  :wink: 

p.s: There are an official package for elementary?

**Comment by varlesh** [comment] 2015-04-12 13:40
Ok ))
I use ppa: https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/pragha

**Comment by flexo3001** [comment] 2015-06-03 14:15
also a problem in pavucontrol. 
![2015-06-03-161421_1366x768_scrot](https://cloud.githubusercontent.com/assets/1415596/7962067/b1624352-0a0b-11e5-998e-3f3d8371dbf3.png)

**Comment by matiasdelellis** [comment] 2015-06-04 21:56
D'Oh!.
Again is a bug of pavucontrol, due a bad change on Gtk devs, which of course will not recognize. and according to them is the blame of designers.. haha. :sweat_smile: 

Well,
Beyond the joke, now fix it. :wink: 

Regards,
Matias

**Comment by flexo3001** [comment] 2015-06-04 22:06
Thank you! By the way pragha is the best music player i ever used.

**Comment by matiasdelellis** [comment] 2015-06-05 00:07
>  Thank you! By the way pragha is the best music player i ever used. 

Thank you very much for your words!. They help to keep going..  ;)

Finally released a new version and should be fixed. Please, test and close it.

Regards,
Matias.

**Comment by matiasdelellis** [comment] 2015-09-24 02:10
Hi @varlesh 
Not added an svg scalable, but add different sizes, that cover all needs.. We can consider it closed?

**Closed** 2015-09-24 15:35 UTC
